# Generated by Django 2.2.1 on 2019-07-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20190605_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemental',
            name='j1',
            field=models.CharField(blank=True, choices=[('9:00 am 10:30 am | Juan Paredes (Bailes festeros por tangos)', '9:00 am 10:30 am | Juan Paredes (Bailes festeros por tangos)'), ('10:35 am - 12:05 pm | Valeriano Paños (Farruca)', '10:35 am - 12:05 pm | Valeriano Paños (Farruca)')], max_length=150),
        ),
        migrations.AlterField(
            model_name='elemental',
            name='j2',
            field=models.CharField(blank=True, choices=[('9:00 am 10:30 am | Pablo Egea', '9:00 am 10:30 am | Pablo Egea'), ('9:00 am - 10:30 am | José Galán', '9:00 am - 10:30 am | José Galán'), ('10:35 am - 12:05 pm | Nazaret Reyes (Tangos)', '10:35 am - 12:05 pm | Nazaret Reyes (Tangos)')], max_length=150),
        ),
    ]
